{
 "title": "Scalability Benchmarking (Flink)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages In Per Second (Kafka)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec_topic_input)"
    }
   ]
  },
  {
   "title": "Messages Out Per Second (Kafka)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_server_brokertopicmetrics_messagesinpersec_topic_output)"
    }
   ]
  },
  {
   "title": "Messages In Per Sec (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job_id) (flink_taskmanager_job_task_numRecordsInPerSecond)"
    }
   ]
  },
  {
   "title": "Messages Out Per Sec (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job_id) (flink_taskmanager_job_task_numRecordsOutPerSecond)"
    }
   ]
  },
  {
   "title": "Record Lag (Kafka Lag Exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(group, topic) (kafka_consumergroup_group_lag > 0)"
    }
   ]
  },
  {
   "title": "Record Lag (Flink)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max"
    }
   ]
  },
  {
   "title": "Number Of Instances (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "Input Queue Length (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, subtask_index) (flink_taskmanager_job_task_buffers_inputQueueLength)"
    }
   ]
  },
  {
   "title": "Backpressure (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_isBackPressured"
    }
   ]
  },
  {
   "title": "Output Queue Length (Flink)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, subtask_index) (flink_taskmanager_job_task_buffers_outputQueueLength)"
    }
   ]
  },
  {
   "title": "Record Lag (Flink Offset Difference)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (flink_taskmanager_job_task_operator_KafkaConsumer_topic_partition_currentOffsets - flink_taskmanager_job_task_operator_KafkaConsumer_topic_partition_committedOffsets)"
    }
   ]
  }
 ]
}